---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/login":
    post:
      summary: logs in a user
      tags:
      - Auth
      parameters: []
      responses:
        '200':
          description: logged in
        '401':
          description: invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - email
              - password
              properties:
                email:
                  type: string
                  example: bob@random.com
                password:
                  type: string
                  example: '123456'
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: http://localhost:3000
