---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/login":
    post:
      summary: logs in a user
      tags:
      - Auth
      security: []
      parameters: []
      responses:
        '200':
          description: logged in
        '401':
          description: invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - email
              - password
              properties:
                email:
                  type: string
                  example: bob@random.com
                password:
                  type: string
                  example: '123456'
  "/api/v1/profile":
    get:
      summary: get current user info using jwt token
      tags:
      - Profile
      security:
      - bearer_auth: []
      responses:
        '200':
          description: profile fetched
        '401':
          description: unauthorized access
  "/api/v1/signup":
    post:
      summary: registers a new user and returns a jwt
      tags:
      - Auth
      security: []
      parameters: []
      responses:
        '201':
          description: user created and token returned
        '422':
          description: validation failed invalid email + password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - email
              - password
              - password_confirmation
              properties:
                email:
                  type: string
                  example: newbob@example.com
                password:
                  type: string
                  example: '123456'
                password_confirmation:
                  type: string
                  example: '123456'
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearer_auth: []
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: http://localhost:3000
